<a href="https://colab.research.google.com/github/Sachin961120/Car-_Prediction/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [4]:
ls

sample_data/


In [5]:
cd/gdrive

/gdrive


In [6]:
ls

MyDrive/


In [7]:
cd MyDrive/

/gdrive/MyDrive


In [8]:
ls

'Adobe Scan 23 Apr 2021 (1).pdf'  'Python QP.docx'
'Adobe Scan 23 Apr 2021 (2).pdf'  'R Fundamentals_ClassCode.R'
'Adobe Scan 23 Apr 2021 (3).pdf'  'Sachin Chavan 0102-290220-15.pdf'
'Adobe Scan 23 Apr 2021.pdf'      'Sachin Chavan 0401-080820-12.pdf'
'Case study-Sirius XM Radio.pdf'  'Sachin Chavan 0601-100421-01 (1).pdf'
 Certificate.jpg                  'sachin mark sheet.pdf'
 Certificate.pdf                  'Sachin_Resume (1).pdf'
 Churn_Modelling.csv               Sachin_Resume.pdf
'Colab Notebooks'/                 SquarePic_20200621_20344275.jpg
 Diploma_certificate.pdf           ssc_certificate.pdf
 IMG_20210427_154703.jpg          'Untitled folder'/
 Last_Year_Certificate.pdf


In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import keras 
from keras.models import Sequential
from keras.layers import Dense, Activation,Embedding,Flatten, BatchNormalization
from keras.layers import LeakyReLU, PReLU, ELU
from keras.activations import sigmoid, relu
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier

In [42]:
df=pd.read_csv('Churn_Modelling.csv')

In [43]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [44]:
#shape of data
df.shape

(10000, 14)

In [45]:
#checking for null values in each columns
for col in df.columns:
  print(col,":",df[col].isnull().sum())

RowNumber : 0
CustomerId : 0
Surname : 0
CreditScore : 0
Geography : 0
Gender : 0
Age : 0
Tenure : 0
Balance : 0
NumOfProducts : 0
HasCrCard : 0
IsActiveMember : 0
EstimatedSalary : 0
Exited : 0


In [46]:
#iloc will Extractrows & columns by number
X=df.iloc[:,3:13]
y=df.iloc[:,13]

In [47]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [48]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [49]:
#one hot encoding
geography= pd.get_dummies(X['Geography'], drop_first=True)
gender= pd.get_dummies(X['Gender'], drop_first=True)

In [50]:
X=pd.concat([X, geography, gender], axis=1)

In [51]:
X.head()

CreditScore Geography  Gender  Age  ...  EstimatedSalary  Germany  Spain  Male
0          619    France  Female   42  ...        101348.88        0      0     0
1          608     Spain  Female   41  ...        112542.58        0      1     0
2          502    France  Female   42  ...        113931.57        0      0     0
3          699    France  Female   39  ...         93826.63        0      0     0
4          850     Spain  Female   43  ...         79084.10        0      1     0

[5 rows x 13 columns]

In [52]:
X=X.drop(['Geography', 'Gender'], axis=1)

In [53]:
X.head()

CreditScore  Age  Tenure    Balance  ...  EstimatedSalary  Germany  Spain  Male
0          619   42       2       0.00  ...        101348.88        0      0     0
1          608   41       1   83807.86  ...        112542.58        0      1     0
2          502   42       8  159660.80  ...        113931.57        0      0     0
3          699   39       1       0.00  ...         93826.63        0      0     0
4          850   43       2  125510.82  ...         79084.10        0      1     0

[5 rows x 11 columns]

In [54]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

In [55]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

In [56]:
sc= StandardScaler()

In [57]:
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [58]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [59]:
#initialising the ANN
classifier= Sequential()

In [60]:
#Adding the input layer and hidden layer
#units are hidden layers
#kernel_initializer indicates how your weights should be initialize
#all the hidden layers should have relu or leakyrelu to prevents vanishing gradient problem
#input_dim means inputs 
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation='relu', input_dim= 11))

In [61]:
#Adding  the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation='relu'))

In [62]:
#Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation='sigmoid'))

In [63]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 6)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [66]:
#compiling the ANN 
#there are mutliple optimizer techniques adam is best and is most popular one
#when our output is either 0 or 1 we use binary_crossentropy, if your has multiple category so you can use category process
classifier.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [68]:
#Fitting the ANN to training set
#validation_split to test the model separtely
#batch  size is use so that computational power become less, more amount of record you dont have to load at one time
model_history= classifier.fit(X_train, y_train, validation_split=0.33, batch_size=10, epochs=100) 

Epoch 1/100
536/536 [==============================] - 15s 3ms/step - loss: 0.7181 - accuracy: 0.5736 - val_loss: 0.5050 - val_accuracy: 0.7963
Epoch 2/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.8058 - val_loss: 0.4518 - val_accuracy: 0.8065
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4383 - accuracy: 0.8085 - val_loss: 0.4259 - val_accuracy: 0.8107
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4096 - accuracy: 0.8261 - val_loss: 0.4091 - val_accuracy: 0.8194
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4047 - accuracy: 0.8243 - val_loss: 0.3950 - val_accuracy: 0.8277
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3823 - accuracy: 0.8430 - val_loss: 0.3844 - val_accuracy: 0.8364
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3658 - accuracy: 0.8576 - val_loss: 0.3776 - val_accuracy: 0.838

In [69]:
#predicting test set results
y_pred= classifier.predict(X_test)
y_pred=(y_pred > 0.5)

In [72]:
#Making confusion matrix
cm= confusion_matrix(y_test, y_pred)

In [73]:
cm

array([[1495,  100],
       [ 188,  217]])

In [75]:
#calculate the Accuracy
score= accuracy_score(y_pred, y_test)

In [76]:
score

0.856

In [78]:
##### HYPER PARAMETER TUNNING

In [92]:
def create_model(layers, activation):
  model= Sequential()
  for i, nodes in enumerate (layers):
    if i== 0:
      model.add(Dense(nodes, input_dim=X_train.shape[1]))
      model.add(Activation(activation))
      model.add(Dropout(0.3)) 
    else:
      model.add(Dense(nodes))
      model.add(Activation(activation))
      model.add(Dropout(0.3))
  model.add(Dense(units=1, kernel_initializer='glorot_uniform',activation='sigmoid' ))
  model.compile(optimizer='adam', loss= 'binary_crossentropy',metrics=['accuracy'])
  return model
model= KerasClassifier(build_fn= create_model, verbose=0)
layers= [[20],[40,20], [45,30,15]]
activations=['sigmoid', 'relu']
param_grid= dict(layers=layers, activation=activations, batch_size=[128,256], epochs=[30])
grid= GridSearchCV(estimator=model, param_grid=param_grid, cv=5)

In [95]:
grid_result=grid.fit(X_train, y_train)

In [97]:
grid_result

GridSearchCV(cv=5, error_score=nan,
             estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x7fe5f39088d0>,
             iid='deprecated', n_jobs=None,
             param_grid={'activation': ['sigmoid', 'relu'],
                         'batch_size': [128, 256], 'epochs': [30],
                         'layers': [[20], [40, 20], [45, 30, 15]]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [99]:
print(grid_result.best_score_,  grid_result.best_params_)

0.8565000057220459 {'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': [45, 30, 15]}


In [102]:
pred_yy= grid_result.predict(X_test)
y_predd= (pred_yy > 0.5)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [103]:
cmm = confusion_matrix(y_predd, y_test)
cmm

array([[1543,  219],
       [  52,  186]])

In [104]:
score=accuracy_score(y_predd, y_test)
score

0.8645